name    'gusson/nsswitch'
version '0.1.0'
source 'git://github.com/gusson/puppet-module-nsswitch.git'
author 'gusson'
license 'Apache License, Version 2.0'
summary 'module to manage nsswitch.conf'
description 'Provides the means to manage nsswitch.conf on Linux and Solaris.'
project_page 'https://github.com/gusson/puppet-module-nsswitch'

dependency 'puppetlabs/stdlib', '>= 3.2.x'
